baseURL = 'https://pirateschool.fm/'
languageCode = 'en-au'
title = 'Pirate School'
theme = "monochrome"

[params]
	color_scheme = "dark"
	enable_zooming_js = false

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			hardWraps = true
			xhtml = true
			unsafe = true

[[menu.navbar]]
	identifier = "apple"
	name = "Apple Podcasts"
	url = "#"
	weight = 10
			
[[menu.navbar]]
	identifier = "spotify"
	name = "Spotify"
	url = "#"
	weight = 20
			
[[menu.navbar]]
	identifier = "overcast"
	name = "Overcast"
	url = "#"
	weight = 30
			
[[menu.navbar]]
	identifier = "rss"
	name = "RSS"
	url = "#"
	weight = 40